language: python
python:
  - "3.7"
install:
  - pip install coverage
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
  
script:
  - coverage run -m pytest --cov-report=xml --cov=.

after_success:
  - codecov
